version: 0.2

phases:
  install:
    commands:
      - git clone https://github.com/Kode/nodejs_bin.git
      - nodejs_bin/copysysbin.sh
  build:
    commands:
      - echo Build started on `date`
      - nodejs_bin/node make.js --kore . --from Tests/Empty --noshaders --compile
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - hello.out